### ISSUE TITLE
Enable SIMD instructions for R packages

### ISSUE THREAD

**Issue by MarcusKlik** [ChingChuan-Chen/RcppBlaze#3]
Hi @ChingChuan-Chen, what a great idea to wrap Blaze in an R package! 

I have a question about compiling the code for SIMD instructions. I can see from your [Makevars](https://github.com/ChingChuan-Chen/RcppBlaze/blob/master/src/Makevars#L2-L3) that you are enabling OpenMP compiler flags. But how are the SIMD compiler options enabled for package building?

And is there a way for easy testing of the highest available SIMD instructions set?

Thanks for your time and for your work on RcppBlaze!

**Comment by ChingChuan-Chen** [comment]
Hi, I don't know what is SIMD, but I try to understand from the document of Blaze at [Blaze VectorType Document](https://bitbucket.org/blaze-lib/blaze/wiki/Vector%20Types):
> For instance, assuming that AVX is available, then two aligned, padded, 3-dimensional vectors of double precision values can be added via a single SIMD addition instruction.

So I think that I can enable AVX in compiling, so I can use SIMD. Therefore, you can refer the following code to enable AVX by give `PKG_CXXFLAGS`:

```r
library(Rcpp)
Sys.setenv("PKG_CXXFLAGS"=paste("-fopenmp -O2 -mavx"))
code <- '
#include "RcppBlaze.h"
// [[Rcpp::depends(RcppBlaze)]]
// [[Rcpp::export]]
void check_avx() {
  #if defined(__AVX__)
    Rcpp::Rcout << "AVX is enabled!" << std::endl;
  #else
    Rcpp::Rcout << "AVX is disabled!" << std::endl;
  #endif
}'
sourceCpp(code = code)
check_avx()
# AVX is enabled!
```

Hope this is helpful for you.

PS: Also you can enable AVX2 in same way.  
PS2: If you want to build package with AVX, please add `-mavx` in `Makevars`.
PS3: SIMD is also used by enabling SSE, it is enabled by R if it is supported.

**Comment by MarcusKlik** [comment]
Hi @ChingChuan-Chen, thanks a lot for your elaborate answer!

Great, so you can just specify the appropriate SIMD instruction flags both in 'on-the-fly' compilation with Rcpp and in `Makevars`. Are you planning to include those flags in the Makevars for your package? If  I understand your answer correctly, your package will be enabled for using the Blaze SIMD instructions when you add those flags to `Makevars`. Or won't the package compile when a user doesn't have an appropriate CPU ?

On my system (Windows 10 on core i5 CPU), your package builds fine with the -mavx2 flag enabled.

The `Makevars` file:

```r
PKG_CXXFLAGS=-I../inst/include $(SHLIB_OPENMP_CXXFLAGS) -mavx2
PKG_LIBS=$(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS) $(SHLIB_OPENMP_CXXFLAGS)
```

Building the package:

```r
* installing to library 'C:/Users/Mark/Documents/R/R-3.4.1/library'
* installing *source* package 'RcppBlaze' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"C:/Users/Mark/DOCUME~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/Mark/Documents/R/R-3.4.1/library/Rcpp/include" -I"C:/Users/Mark/Documents/R/R-3.4.1/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -fopenmp -mavx2   -O2 -Wall  -mtune=core2 -c RcppBlaze.cpp -o RcppBlaze.o
c:/Rtools/mingw_64/bin/g++  -I"C:/Users/Mark/DOCUME~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/Mark/Documents/R/R-3.4.1/library/Rcpp/include" -I"C:/Users/Mark/Documents/R/R-3.4.1/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -fopenmp -mavx2   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -I"C:/Users/Mark/DOCUME~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/Mark/Documents/R/R-3.4.1/library/Rcpp/include" -I"C:/Users/Mark/Documents/R/R-3.4.1/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -fopenmp -mavx2   -O2 -Wall  -mtune=core2 -c fastLm.cpp -o fastLm.o
c:/Rtools/mingw_64/bin/gcc  -I"C:/Users/Mark/DOCUME~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/Mark/Documents/R/R-3.4.1/library/Rcpp/include" -I"C:/Users/Mark/Documents/R/R-3.4.1/library/BH/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c registerDynamicSymbols.c -o registerDynamicSymbols.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o RcppBlaze.dll tmp.def RcppBlaze.o RcppExports.o fastLm.o registerDynamicSymbols.o -LC:/Users/Mark/DOCUME~1/R/R-34~1.1/bin/x64 -lRlapack -LC:/Users/Mark/DOCUME~1/R/R-34~1.1/bin/x64 -lRblas -lgfortran -lm -lquadmath -fopenmp -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/Users/Mark/DOCUME~1/R/R-34~1.1/bin/x64 -lR
installing to C:/Users/Mark/Documents/R/R-3.4.1/library/RcppBlaze/libs/x64
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (RcppBlaze)
```

And a check for activation of intrinsics:

```r
RcppBlaze:::Blaze_AVX2()
#> [1] TRUE

RcppBlaze:::Blaze_AVX()
#> [1] TRUE

RcppBlaze:::Blaze_FMA()
#> [1] FALSE

RcppBlaze:::Blaze_MIC()
#> [1] FALSE

RcppBlaze:::Blaze_SSE()
#> [1] TRUE
```

thanks for your answer and great work!

**Comment by ChingChuan-Chen** [comment]
Hi, @MarcusKlik 

Sorry, I can't do that since the avx or avx2 are not supported by all cpus. But what you can do is to specify the `CXXFLAGS` in `~/.R/Makevars` file.

**Comment by MarcusKlik** [comment]
Hi @ChingChuan-Chen, thanks. So I guess the only way to actually serve 'out-of-the-box' SIMD optimization (to users that download an R package from CRAN for example) is to compile multiple versions (e.g. AVX2, SSE2, no-SIMD versions) of the critical code and use a run-time CPU dispatcher.

Perhaps that's why there are not many SIMD enabled R packages out there :-).

I will attempt to make such a dispatcher in `fst` for use with `Blaze` or `vectorclass` for the most critical parts in a future release (following Agner Fog's scheme in his [optimizing C++ tutorial](http://agner.org/optimize/optimizing_cpp.pdf)), perhaps you would be interested in taking a closer look at that also for use in your own package when that time comes?

Anyway, thanks a lot for your answers and your work with `Blaze`, good luck to you on your project!

**Comment by ChingChuan-Chen** [comment]
Maybe you can ask the author of Rcpp, Dirk Eddelbuettel, about this, I think that he can give some helpful information.

**Comment by MarcusKlik** [comment]
Thanks, indeed he probably has though that through already :-)

many greetings
